# Intro to NumPy and Matplotlib (for plotting)
* Allows fast matrix operations and can avoid looping

-  [based on this numpy quickstart guide](https://docs.scipy.org/doc/numpy/user/quickstart.html)

-  [full list of routines](https://docs.scipy.org/doc/numpy-dev/reference/routines.html#routines)

In [2]:
# import numpy and other stuff for this tutorial
import numpy as np
from numpy import pi
import matplotlib.pyplot as plt
from scipy.stats import norm

## initialize array and a few basic operations

In [ ]:
# set up an array and figure out shape...    
my_array = np.arange(10)    # the interval includes `start` but excludes `stop`, overal interval [start...stop-1]
print(my_array)
my_array.shape     

In [ ]:
# reshape array
my_array = np.arange(10)
print(my_array.shape)   

my_array = my_array.reshape(2,5)   # why is (2,5) and (5,2) ok but (2,6) not ok? 
print(my_array.shape)   
print(my_array)

# can also directly re-assign the shape
my_array.shape = 5,2
print(my_array.shape)
print(my_array)

In [ ]:
# neat trick...can also reshape with 'shape' and use a -1 which means 'whatever works' 
my_array = np.arange(42)
my_array.shape = 2,3,-1
print(my_array)
my_array.shape

## data types (and remember - strong typed language)

In [ ]:
print('Dims of data: ', my_array.ndim)                              # number of dims
print('Size of each element (bytes): ', my_array.itemsize)          # size of each element in bytes
print('Total number of elements in array: ', my_array.size)         # total number of elements in array
print('Name of data type: ', my_array.dtype.name)                   # name of data type (float, int32, int64 etc)

In [ ]:
# will infer data type based on input values...here we have 1 float so the whole thing is float
float_array = np.array([1.2,2,3])  
float_array.dtype.name             # or np.dtype

<div class="alert alert-success">
what happens if you initialize with floating point numbers but you declare an int data type?
</div>

In [ ]:
int_array = np.array([[1.1,2.7,3.4], [6.9,7.5,8.2]], dtype = 'int32')   # complex, float32, float64, int32, uint32 (unsigned int32), etc
int_array

## Allocate arrays of zeros, ones or rand to pre-allocate the memory before filling up later 

#### handy when you know what size you need, but you're not ready to fill it up yet...
* saves you from dynamically resizing the matrix during analysis, which is very slow
* if you fill with zeros/ones, can be handy for matrix operations
* filling with NaNs is also handy to check for errors in how you fill up the matrix

In [ ]:
# note the () around the dims because you specify as a tuple...default type is float64
zero_array = np.zeros( (3,4) )   
print('Data type:', zero_array.dtype)

In [ ]:
# explicitly declare data type
zero_array = np.zeros( (3,4), dtype=np.int32)   
print('Data type:', zero_array.dtype)
print(zero_array)

In [ ]:
# ones
# note the 3D output below...4, 4x4 squares of floating point 1s...
np.ones( (4,4,4), dtype=np.float64 ) * 10     

### Initialize the array to some arbitrary value with np.full
* useful for filling up array with 'not a number' (nan)
* super useful for bug checking

In [ ]:
# nan's!!! (not a number)
np.full( (10,10), np.nan)

#### example of bug checking with NaNs. Suppose you allocate an array that is 10 elements long and you want to fill it up. However, you make a mistake and don't actually fill up all of the slots. Easy to spot-check this if you init the array with NaNs

In [ ]:
x = np.full( (10), np.nan)

# then fill it up with all 1s (incorrectly)
x[0:8] = 1
print(x)

# spot-check to see if there is an error
if np.any(np.isnan(x)):
    print('messed up array filling!!!')

## Can also create sequences of numbers using arange...
* For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.
* same notation: start, stop, step

In [ ]:
# can specify start, stop and step
seq_array = np.arange(0,30,5)     # start, stop (exclusive), step size
print(seq_array)
# note that 30 is not in there...

In [ ]:
seq_array = np.arange(0,10,.56788)    # decimal input is ok too (and again - stop is NOT included)
print(seq_array)

<div class="alert alert-info">
Because of machine precision issues, sometimes hard to predict how many elements will end up in an array when initialized using arange...so often better to specify a sequence based on start point, stop point, and the exact number of elements that you want (or the number of steps between start and stop). linspace (linear spacing) is the function to do this, and note that unlike arange that ends < stop point, linspace will always end exactly at the specified stop point. 
</div>

In [ ]:
# start, stop, number of linearly spaced steps between start and stop...note that start AND stop included!
lin_array = np.linspace(0,180,9) 
print(lin_array)

## Common use of linspace in this class...eval a function over an interval. quick intro to basic plotting here too...

In [ ]:
x = np.linspace(0, 2*pi, 360)
sin_wave = np.sin(x)

# plotting - note conversion of x values back to degrees for easier human readability
h = plt.plot(x*180/pi, sin_wave, 'k-', linewidth = 4)    # specify x,y data...convert rad to deg for x-axis

# label each axis and give it a title
plt.xlabel('angle (deg)')
plt.ylabel('Amplitude')
plt.title('Sin Wave')
plt.grid(1)
plt.show()


### Figure out how to set/change attributes of the plot (similar to matlab)

In [ ]:
# figure out all settings to tweak...
plt.setp(h) 

In [ ]:
# plotting
h = plt.plot(x*180/pi, sin_wave, 'k-', linestyle=':', linewidth = 2)    # specify x,y data...convert rad to deg for x-axis

# can also specific style attributes like this...
plt.setp(h, marker='v')
plt.setp(h, markersize=10)
plt.setp(h, markerfacecolor='r')

# label each axis and give it a title
plt.xlabel('angle (deg)')
plt.ylabel('Amplitude')
plt.title('Sin Wave')
plt.grid(1)
plt.show()

## initializing arrays with random numbers...use np.random.rand and np.random.randn
* will use this a LOT to simulate data
* specify size of desired array rows x columns

In [ ]:
rand_array = np.random.rand(2,4)   # drawn from uniform over [0,1]
print(rand_array)

#### neat trick to get a random assortment of 0s and 1s (e.g., to simulate coin flips in a model)

In [ ]:
np.round(rand_array)
print(np.round(rand_array))

#### randn: draw from a normal with mean, variance
* To change mu, sig^2, use: mu + (np.random.randn(x,y) * np.sqrt(sig^2)) 

In [ ]:
rand_array = np.random.randn(2,6)  # drawn from normal with mean 0 and variance 1
print(rand_array)

## use randn to generate draws from a normal distribtion with mean = mu and std = sig and then plot...

In [ ]:
# shift the mean and scale the variance for a N(mu,var)
samples = 1000
mu = 4
sig = 20
num_bins = 30

# generate the array of rand numbers 
rand_array = mu + (sig * np.random.randn(samples))   # drawn from normal with mean mu and variance sig

# make multiple axes...
fig, (ax1,ax2) = plt.subplots(2,1, sharex=True)

# generate the histogram, note density == 1 (so unit area)
ax1.hist(rand_array, num_bins, density=0)
ax1.set_ylabel('Trial count')

# generate a pdf evaled at 'bins' to draw a smooth function - this works because we used randn to generate the data
n, bins, patches = ax2.hist(rand_array, num_bins, density=1)

y = norm.pdf(bins, mu, sig)
ax2.plot(bins, y, 'k--', linewidth = 6)
ax2.set_xlabel('Random Variable')
ax2.set_ylabel('Probability density')

# show the plot
plt.show()


## Simple elementwise arithmetic operations like + and - work on corresponding elements of arrays. More on linear algebra in separate tutorial

In [ ]:
x = np.linspace(0,2*pi,360)
y = np.sin(x)

plt.subplot(3, 1, 1)
plt.plot(x, x, 'k--')
plt.title('X')
plt.ylabel('Amplitude')
plt.show()

plt.subplot(3, 1, 2)
plt.plot(x, y, 'k--')
plt.title('Y')
plt.xlabel('angle')
plt.ylabel('Amplitude')
plt.show()

plt.subplot(3, 1, 3)
plt.plot(x, x-y, 'k--')
plt.title('X-Y')
plt.xlabel('angle')
plt.ylabel('Amplitude')

plt.show()

## Some operations that can modify an existing array


<div class="alert alert-info">
when dealing with muliple arrays of different data types, resulting array will take the form of the highest precision input array (upcasting)!
</div>

In [ ]:
x = np.arange(10, dtype='int32')
print('x data type: ', x.dtype)

y = np.random.randn(1,10)
print('y data type: ', y.dtype)

# now multiply the int32 array with the float64 array and answer should be the higher precision of the two (float64)
z = x * y 
print(z)
print('z data type: ', z.dtype)

## Unary operations implemented as methods of the ndarray class

In [5]:
x = np.arange(10).reshape(2,5)   # 2 x 5 matrix

print(x)

x.sum()                          # sum of all elements
print(x.sum(axis=0))             # sum of each column (across 1st dim)
print(x.sum(axis=1))             # sum of each row (across 2nd dim)
print(x.sum(0))                  # don't need the axis arg, but always use it!

x.prod()

[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 5  7  9 11 13]
[10 35]
[ 5  7  9 11 13]


0

## Other common operations...

In [ ]:
x = np.random.rand(12,3)  
print(x.min())           # min of entire matrix
print(x.min(axis=0))          # min across 1st dim
print(x.max(1))          # max across 2nd dim
print(x.cumprod(1))      # cumulative product across 2nd dim

## Set logic....

In [ ]:
x = np.arange(20)
y = np.linspace(0, 20, 21)
print(x)
print(y)

z = np.union1d(x,y)
print(z)

z = np.intersect1d(x,y)
print(z)

z = np.unique([np.append(x,y)])
print(z)

## Indexing and slicing and iterating in NumPy

In [ ]:
# create a 1d array
x = np.linspace(0,9,10)
print(x)
x[1]                     # just the second entry, remember 0 based indexing

# specific start and stop points (exclusive)
x[0:2]                   # the first and second entries in the array, so N>=0 and N<2 (note the < upper bound - not inclusive)

# assign the 2nd - 4th element to 100 (index 1,2,3)
x[1:4] = 100               
print(x[1:4])

# start, stop, step interval
print(x[0:8:2])

# reverse x
print(x[::-1])

# iterate over all elements in x
for i in x:
    print(i*3)    # then i takes the value of each element in x
    

## multidimentional array indexing, slicing etc

In [ ]:
x = np.round(np.random.rand(10,5)*10)   # generate a matrix of uniformly distributed random numbers over 0:10
print(x)

In [ ]:
x[0,0]     # first row, first column
x[2,3]     # third row, 4th column

In [ ]:
x[:, 3]    # all entries in the 4th column 
x[3, :]    # all entries in the 4th row
x[0:2, 4]  # first two entries of the 5th column
x[6, 2:4]  # 7th row, 3rd and 4th entries. 

In [ ]:
x[6]       # if not all dims specified then missing values are considered complete slices
x[6,]      # these three ways of writing all do the same thing...
x[6,:]

In [ ]:
# tricks...
print('last row: ', x[-1,:])     # last row
print('last column: ', x[:,-1])  # last column
print('last entry: ', x[-1,-1])  # last value

### iterating goes over the first dim (rows)

In [ ]:
for r in x:
    print(r)

In [ ]:
# can also iterate over all entries in the array using 'flat'
# will proceed along 1st row, then to 2nd row, etc. 
for a in x.flat:
    print(a)

### pull out subset of rows and columns

In [ ]:
# generate a matrix of random numbers over 0-1
x = np.random.rand(4,3) 
print(x)

# first two rows - note that you don't have to specify the 2nd dim - and note that 
# '2' here means rows 0 and 1 (not 0 through 2!)
y = x[:2] 
print('\n', y)

# can also take the last two rows...in the same manner...in this case rows 3 and 4
y = x[2:] 
print('\n', y)

# first two rows, 1st column
y = x[:2,0] 
print('\n', y)

# rows 3 - end, columns 2 - end
y = x[2:,1:]
print('\n', y)

### important - unlike a list, slicing an array creates a view of it! if you change the view, you also will change the original data!
* use copy just to be safe if this is indeed what you want to happen. 

In [ ]:
x = np.random.randn(4,4)

# assign using slicing...
z = x[:]

# change all values in z using [:]
z[:]=100     # so if you change data in z it will also change in x

print(x)

### use copy instead if you want independent data...

In [ ]:
x = np.random.randn(4,4)

# assign using slicing...
z = x.copy()

# change all values in z using [:]
z[:]=100     # so if you change data in z it will also change in x

print(x)

## Concatenating arrays (stacking)

In [7]:
# use floor and ceil to make two 5x6 arrays of rand numbers
x = np.floor(np.random.rand(5,6)*10)
y = np.ceil(np.random.rand(5,6)*2)

# vertical stacking of arrays...will make a 10x6
z = np.vstack((x,y))
print('shape of z after vert stacking x,y: ', z.shape)

# horizontal stacking of arrays...will make a 5x12
z = np.hstack((x,y))
print('shape of z after horizontal stacking x,y: ', z.shape)

# column stacking of arrays...will make a 5x12
z = np.column_stack((x,y))
print('shape of z after column stacking x,y: ', z.shape)

# concatenate allows stacking along specified dim
z = np.concatenate((x,y),axis=0)   # vstack - stack rows on top of each other
print('shape of z after vertical concat x,y: ', z.shape)

z = np.concatenate((x,y),axis=1)   # hstack - stack columns next to each other
print('shape of z after horizontal concat x,y: ', z.shape)


shape of z after vert stacking x,y:  (10, 6)
shape of z after horizontal stacking x,y:  (5, 12)
shape of z after column stacking x,y:  (5, 12)
shape of z after vertical concat x,y:  (10, 6)
shape of z after horizontal concat x,y:  (5, 12)


### Fancy indexing...using arrays to index arrays - used all the time in data analysis...
* fancy indexing always makes a COPY of the data (unlike slicing which creates a view)!!! 

In [ ]:
# define an array
x = np.random.rand(3,4)

print(x)

# index array - can be a tuple, in this case to pull out the lower right entry
y = (2,3)

# index
x[y]

In [ ]:
# this will extract the 3rd row, then the 2nd row, then the first row (flipud)
print(x[[2,1,0]])

In [ ]:
# or can pass in multiple arrays...will return a 1D array 
# corresponding to each set of tuples (1,1) and (2,2) in this case
print(x)
x[[1,2],[1,2]]

## A few more notes about shape manipulation

In [ ]:
x = np.round(np.random.randn(6,8)*5)   # generate some random data from N(0,5), then round 
print(x)

# flatten the array
y = x.ravel()   
print('Shape of x: ', x.shape, '\nShape of flattened x:', y.shape)  # newline example + multiple outputs...

# reshape
x = x.reshape(12,4)   # 48 element array reshaped from a 6x8 to a 12x4

# transpose - swap row/column
print(x.T)
print('Reshaped x: ', x.shape, '\nReshaped x transposed: ', x.T.shape)